// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuacwyquxilikqnfkusx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1YWN3eXF1eGlsaWtxbmZrdXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwMzY0ODIsImV4cCI6MjA1MDYxMjQ4Mn0.D4mKhB3LP4vYBkzp85xmso34PV90DOtHMC1CDpsHrCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);